Repository AY1920S1-CS2113T-F09-3/main, pull requests merged in 2019-10, with the labels that each got.

#146 JUnit test for Morphed Classes
  src/test/java/commands/AddCommandTest.java
  src/test/java/eggventory/StockTypeTest.java
Labels: type.Task

#173 Parser accepts any amount of whitespace between words
  data/saved_tasks.txt
  src/main/java/eggventory/Parser.java
Labels: type.Task

#208 Implement delete functionality
  src/main/java/eggventory/Eggventory.java
  src/main/java/eggventory/StockList.java
  src/main/java/eggventory/commands/DeleteCommand.java
  src/main/java/eggventory/items/StockType.java
  src/main/java/eggventory/parsers/ParseDelete.java
  src/main/java/eggventory/parsers/Parser.java
Labels: type.Task

#223 Implement base code for "edit", "edit stock", "edit stocktype" functionality,
  src/main/java/eggventory/StockList.java
  src/main/java/eggventory/commands/edit/EditStockCommand.java
  src/main/java/eggventory/commands/edit/EditStockTypeCommand.java
  src/main/java/eggventory/enums/CommandType.java
  src/main/java/eggventory/enums/Property.java
  src/main/java/eggventory/items/Stock.java
  src/main/java/eggventory/items/StockType.java
  src/main/java/eggventory/parsers/ParseEdit.java
  src/main/java/eggventory/parsers/Parser.java
  src/test/java/eggventory/StockTypeTest.java
Labels: type.Task, type.Test

#269 Store csv
  .gitignore
  data/saved_stocks.csv
  data/saved_stocktypes.csv
  src/main/java/eggventory/Eggventory.java
  src/main/java/eggventory/logic/HelpCommand.java
  src/main/java/eggventory/logic/commands/CommandDictionary.java
  src/main/java/eggventory/logic/commands/add/AddStockTypeCommand.java
  src/main/java/eggventory/logic/commands/edit/EditStockCommand.java
  src/main/java/eggventory/logic/parsers/ParseEdit.java
  src/main/java/eggventory/logic/parsers/Parser.java
  src/main/java/eggventory/model/StockList.java
  src/main/java/eggventory/model/items/Stock.java
  src/main/java/eggventory/model/items/Stock.java.orig
  src/main/java/eggventory/model/items/StockType.java
  src/main/java/eggventory/storage/Storage.java
  src/test/java/eggventory/StockTypeTest.java
  src/test/java/eggventory/commands/edit/EditStockCommandTest.java
  src/test/java/eggventory/commands/help/Help.txt
  src/test/java/eggventory/commands/help/HelpAdd.txt
  src/test/java/eggventory/commands/help/HelpDelete.txt
  src/test/java/eggventory/commands/help/HelpEdit.txt
  src/test/java/eggventory/commands/help/HelpFind.txt
  src/test/java/eggventory/commands/help/HelpList.txt
  src/test/java/eggventory/commands/help/HelpLoan.txt
  src/test/java/eggventory/commands/help/HelpLost.txt
  src/test/java/eggventory/commands/help/HelpRedo.txt
  src/test/java/eggventory/commands/help/HelpUndo.txt
  src/test/java/eggventory/items/StockTest.java
  src/test/java/eggventory/logic/commands/ByeCommandTest.java
  src/test/java/eggventory/logic/commands/CommandTest.java
  src/test/java/eggventory/logic/commands/FindCommandTest.java
  src/test/java/eggventory/logic/commands/ListCommandTest.java
  src/test/java/eggventory/logic/commands/add/AddPersonCommandTest.java
  src/test/java/eggventory/logic/commands/add/AddStockCommandTest.java
  src/test/java/eggventory/logic/commands/add/AddStockTypeCommandTest.java
  src/test/java/eggventory/logic/commands/delete/DeleteStockCommandTest.java
  src/test/java/eggventory/logic/commands/delete/DeleteStockTypeCommandTest.java
  src/test/java/eggventory/logic/commands/edit/EditStockCommandTest.java
  src/test/java/eggventory/logic/commands/edit/EditStockTypeCommandTest.java
  src/test/java/eggventory/logic/commands/help/HelpCommandTest.java
  src/test/java/eggventory/model/items/StockTest.java
  src/test/java/eggventory/stubs/UiStub.java
Labels: type.Bug

#276 Ug in Markdown
  data/saved_stocks.csv
  data/saved_stocktypes.csv
  docs/CS2113T-F09-3-Eggventory-UG.md
Labels: type.Task
